# Generated by Django 4.2.2 on 2023-07-12 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0004_loan_comments_alter_loan_interestrate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='comments',
            new_name='Comments',
        ),
        migrations.AddField(
            model_name='loan',
            name='LoanNumber',
            field=models.CharField(default='001', max_length=20),
        ),
        migrations.CreateModel(
            name='LoanReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnAmount', models.IntegerField(verbose_name='Return Amount')),
                ('ReturnDate', models.DateField(default=django.utils.timezone.now, verbose_name='Return Date')),
                ('Comments', models.TextField(blank=True, null=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('Loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loaner.loan', verbose_name='Loan Account')),
            ],
        ),
    ]
