# Generated by Django 4.2.2 on 2023-07-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0007_alter_loan_options_alter_loan_loannumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanreturn',
            name='Loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loaner.loan', verbose_name='Loan Account'),
        ),
    ]
