# Generated by Django 4.2.2 on 2023-07-16 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0008_alter_loanreturn_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanreturn',
            name='Loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loaner.loan', verbose_name='Loan Account'),
        ),
    ]
