# Generated by Django 4.2.2 on 2023-07-17 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0009_alter_loanreturn_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMonthlyInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstallmentAmount', models.IntegerField(verbose_name='Installment Amount')),
                ('InstallmentPenalty', models.IntegerField(default='1', verbose_name='Installment Penalty Rate')),
                ('AnyDiscount', models.IntegerField(default='0', verbose_name='Any Discount')),
                ('InstallmentDate', models.DateField(default=django.utils.timezone.now, verbose_name='Next Installment Date')),
                ('Comments', models.TextField(blank=True, null=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('Loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loaner.loan', verbose_name='Loan Account')),
            ],
        ),
    ]
