# Generated by Django 4.2.2 on 2023-07-17 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0010_loanmonthlyinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmonthlyinstallment',
            name='InstallmentNextDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Next Installment Date'),
        ),
        migrations.AlterField(
            model_name='loanmonthlyinstallment',
            name='InstallmentDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Installment Date'),
        ),
    ]
