# Generated by Django 4.2.2 on 2023-07-17 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0012_remove_loanmonthlyinstallment_installmentnextdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmonthlyinstallment',
            name='InstallmentMonth',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 10, 8, 42, 804941, tzinfo=datetime.timezone.utc), verbose_name='Installment Month'),
        ),
    ]
