# Generated by Django 4.2.2 on 2023-07-17 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0013_alter_loanmonthlyinstallment_installmentmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmonthlyinstallment',
            name='InstallmentMonth',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 10, 18, 39, 962710, tzinfo=datetime.timezone.utc), verbose_name='Installment Month'),
        ),
        migrations.AlterField(
            model_name='loanmonthlyinstallment',
            name='InstallmentPenalty',
            field=models.IntegerField(default='0', verbose_name='Installment Penalty Rate'),
        ),
    ]
