# Generated by Django 4.2.2 on 2023-07-18 07:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0014_alter_shareholderinstallment_comments'),
        ('loaner', '0015_alter_loanmonthlyinstallment_installmentmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmonthlyinstallment',
            name='InstallmentMonth',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 7, 54, 14, 293180, tzinfo=datetime.timezone.utc), verbose_name='Installment Month'),
        ),
        migrations.CreateModel(
            name='ReferenceBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BonusAmount1', models.IntegerField(verbose_name='Bonus Amount 1')),
                ('BonusAmount2', models.IntegerField(verbose_name='Bonus Amount 2')),
                ('BonusGivenDate', models.DateField(default=django.utils.timezone.now, verbose_name='Bonus Given Date')),
                ('isPaid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('Comments', models.TextField(blank=True, null=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('Loan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loaner.loan', verbose_name='Loan Account')),
                ('Reference1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Reference_Bonus_One', to='shareholder.shareholder', verbose_name='Reference One')),
                ('Reference2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Reference_Bonus_Two', to='shareholder.shareholder', verbose_name='Reference Two')),
            ],
        ),
    ]
