# Generated by Django 4.2.2 on 2023-07-18 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0016_alter_loanmonthlyinstallment_installmentmonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmonthlyinstallment',
            name='InstallmentMonth',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 8, 25, 10, 46731, tzinfo=datetime.timezone.utc), verbose_name='Installment Month'),
        ),
        migrations.AlterField(
            model_name='referencebonus',
            name='BonusAmount1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus Amount 1'),
        ),
        migrations.AlterField(
            model_name='referencebonus',
            name='BonusAmount2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus Amount 2'),
        ),
        migrations.AlterField(
            model_name='referencebonus',
            name='Loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loaner.loan', verbose_name='Loan Account'),
        ),
    ]
