# Generated by Django 4.2.2 on 2023-07-18 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0017_alter_loanmonthlyinstallment_installmentmonth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencebonus',
            name='PaidMonth',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 8, 29, 54, 43831, tzinfo=datetime.timezone.utc), verbose_name='Paid Month'),
        ),
        migrations.AlterField(
            model_name='loanmonthlyinstallment',
            name='InstallmentMonth',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 8, 29, 54, 43831, tzinfo=datetime.timezone.utc), verbose_name='Installment Month'),
        ),
    ]
