# Generated by Django 4.2.2 on 2023-07-18 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0018_referencebonus_paidmonth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmonthlyinstallment',
            name='InstallmentMonth',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 10, 10, 1, 431750, tzinfo=datetime.timezone.utc), verbose_name='Installment Month'),
        ),
        migrations.AlterField(
            model_name='referencebonus',
            name='Loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loaner.loan', verbose_name='Loan Number'),
        ),
        migrations.AlterField(
            model_name='referencebonus',
            name='PaidMonth',
            field=models.DateField(default=datetime.datetime(2023, 7, 1, 10, 10, 1, 431750, tzinfo=datetime.timezone.utc), verbose_name='Paid Month'),
        ),
    ]
