# Generated by Django 4.2.3 on 2023-08-01 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("loaner", "0021_alter_loanmonthlyinstallment_installmentmonth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanmonthlyinstallment",
            name="InstallmentMonth",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Installment Month"
            ),
        ),
        migrations.AlterField(
            model_name="referencebonus",
            name="PaidMonth",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Paid Month"
            ),
        ),
    ]
