# Generated by Django 4.2.5 on 2023-10-04 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loaner', '0023_alter_loanmonthlyinstallment_installmentamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmonthlyinstallment',
            name='MarginDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Margin Date'),
        ),
    ]
