# Generated by Django 4.2.2 on 2023-06-24 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, verbose_name='User Name')),
                ('firstName', models.CharField(blank=True, max_length=80, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('isMember', models.BooleanField(default=True, verbose_name='Is Member')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
