# Generated by Django 4.2.2 on 2023-06-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0002_alter_shareholder_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareholder',
            old_name='photo',
            new_name='profilePic',
        ),
    ]
