# Generated by Django 4.2.2 on 2023-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0003_rename_photo_shareholder_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='firstName',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='lastName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='profilePic',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Profile Picture'),
        ),
    ]
