# Generated by Django 4.2.2 on 2023-06-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0004_alter_shareholder_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='profilePic',
        ),
    ]
