# Generated by Django 4.2.2 on 2023-06-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0006_shareholder_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareholder',
            old_name='picture',
            new_name='profilePic',
        ),
    ]
