# Generated by Django 4.2.2 on 2023-06-25 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0007_rename_picture_shareholder_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHolderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareNumber', models.IntegerField(default=1, verbose_name='Share Number')),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('registrationAmount', models.IntegerField(default=1000, verbose_name='Registration Fee')),
                ('installmentAmount', models.IntegerField(default=500, verbose_name='Installment Amount')),
                ('shareHolder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shareholder.shareholder', verbose_name='Share Holder')),
            ],
        ),
    ]
