# Generated by Django 4.2.2 on 2023-06-25 09:06

from django.db import migrations, models
import shareholder.models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0008_shareholdersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholdersetting',
            name='shareHolder',
            field=models.IntegerField(verbose_name=shareholder.models.ShareHolder),
        ),
    ]
