# Generated by Django 4.2.2 on 2023-06-25 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0010_alter_shareholdersetting_shareholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareHolderInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstallmentDate', models.DateField(default=django.utils.timezone.now, verbose_name='Installment Date')),
                ('InstallmentAmount', models.IntegerField()),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('shareHolder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shareholder.shareholder', verbose_name='Share Holder')),
            ],
        ),
    ]
