# Generated by Django 4.2.2 on 2023-07-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0011_shareholderinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholderinstallment',
            name='anyDiscount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Consider Discount'),
        ),
        migrations.AddField(
            model_name='shareholderinstallment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareholderinstallment',
            name='havePenalty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Have Penalty'),
        ),
    ]
