# Generated by Django 4.2.2 on 2023-07-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0012_shareholderinstallment_anydiscount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareholderinstallment',
            old_name='anyDiscount',
            new_name='haveDiscount',
        ),
    ]
