# Generated by Django 4.2.2 on 2023-07-01 17:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareholder', '0013_rename_anydiscount_shareholderinstallment_havediscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholderinstallment',
            name='comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
