# Generated by Django 4.2.3 on 2023-07-30 16:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shareholder', '0014_alter_shareholderinstallment_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpensePurpose', models.CharField(max_length=250, verbose_name='Expense Purpose')),
                ('ExpenseDate', models.DateField(default=django.utils.timezone.now, verbose_name='Expense Date')),
                ('ExpenseAmount', models.IntegerField()),
                ('Comments', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('CreatedBy', models.IntegerField(blank=True, null=True)),
                ('DateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('DateLastUpdated', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedBy', models.IntegerField(blank=True, null=True)),
                ('ShareHolder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shareholder.shareholder', verbose_name='Expense By')),
            ],
        ),
    ]
